import type { ContentDashboardModel } from './contracts.js'
import { defaultDashboardVisualContract, trustSectionHtml, visualContractCss, type DashboardVisualContract } from './universal-contract.js'

const escapeHtml = (value: string | number): string => String(value).replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]!)
const formatNumber = (value: number) => new Intl.NumberFormat('zh-CN', { maximumFractionDigits: 0 }).format(value)
const formatPercent = (value: number) => `${(value * 100).toFixed(1)}%`

export function renderOfflineDashboard(model: ContentDashboardModel, options: { visualContract?: DashboardVisualContract; sourceLabel?: string; semanticStatus?: string; evidenceCount?: number } = {}): string {
  const visual = options.visualContract ?? defaultDashboardVisualContract()
  const maxViews = Math.max(...model.trend.map((point) => point.views), 1)
  const trendRows = model.trend.map((point) => `<div class="bar-row"><span>${escapeHtml(point.date.slice(5))}</span><div class="bar-track"><i style="width:${Math.max(2, point.views / maxViews * 100)}%"></i></div><b>${formatNumber(point.views)}</b></div>`).join('')
  const categoryRows = model.categories.map((category) => `<tr><td>${escapeHtml(category.category)}</td><td>${formatNumber(category.published)}</td><td>${formatNumber(category.views)}</td><td>${formatPercent(category.conversionRate)}</td><td>¥${formatNumber(category.revenue)}</td></tr>`).join('')
  const actionRows = model.actions.map((action) => `<article class="action"><b>${action.priority}优先级</b><p><strong>证据：</strong>${escapeHtml(action.evidence)}</p><p><strong>下一步：</strong>${escapeHtml(action.nextStep)}</p><p><strong>预期：</strong>${escapeHtml(action.expectedDirection)}</p></article>`).join('')
  return `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>内容运营看板</title><style>
:root{--ink:#172033;--muted:#667085;--line:#dfe4ed;--brand:#3155c6;--soft:#f5f7fb;--good:#087e65;--warn:#a36106}*{box-sizing:border-box}body{margin:0;background:#f4f6fa;color:var(--ink);font:14px/1.6 "Microsoft YaHei",Arial,sans-serif}.wrap{width:min(1160px,calc(100% - 32px));margin:auto}header{padding:36px 0;background:linear-gradient(135deg,#16244b,#3155c6);color:#fff}h1{margin:0;font-size:30px}.sub{color:#dce7ff;margin:8px 0}.fresh{font-size:12px;color:#c7d5fa}.grid{display:grid;gap:16px}.kpis{grid-template-columns:repeat(4,1fr);margin-top:-22px}.card,section,.action{background:#fff;border:1px solid var(--line);border-radius:12px;padding:20px}.kpi-label,.hint{font-size:12px;color:var(--muted)}.kpi-value{font-size:30px;font-weight:700;margin:6px 0}.positive{color:var(--good)}main{padding:34px 0 60px}section{margin-top:18px}h2{font-size:18px;margin:0 0 14px}.filter{display:flex;gap:12px;align-items:center}.filter span{border:1px solid var(--line);padding:5px 9px;border-radius:999px;color:var(--muted)}.two{grid-template-columns:1.2fr .8fr}.bar-row{display:grid;grid-template-columns:48px 1fr 72px;gap:10px;align-items:center;margin:11px 0}.bar-track{height:10px;background:var(--soft);border-radius:99px;overflow:hidden}.bar-track i{display:block;height:100%;background:var(--brand);border-radius:99px}.diagnostic{border-left:4px solid var(--warn);background:#fff9eb}.actions{grid-template-columns:repeat(3,1fr)}.action{padding:16px}.action b{color:var(--warn)}.action p{margin:7px 0}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid var(--line);text-align:left}th{color:var(--muted);font-size:12px}@media(max-width:760px){.kpis,.two,.actions{grid-template-columns:1fr}.kpis{margin-top:16px}h1{font-size:25px}table{font-size:12px}}@media(prefers-color-scheme:dark){body{background:#101827;color:#edf2ff}.card,section,.action{background:#182236;border-color:#33415a}.bar-track{background:#26334d}.hint,.kpi-label,th{color:#a8b4c9}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}</style></head>
<body><header data-dashboard-role="summary" data-freshness="${escapeHtml(model.freshness)}"><div class="wrap"><h1>内容运营周看板</h1><p class="sub">${escapeHtml(model.timeframe)} · ${escapeHtml(model.conclusion)}</p><span class="fresh">数据更新至 ${escapeHtml(model.freshness.replace('T', ' ').slice(0, 19))}</span></div></header><main class="wrap">
<section data-dashboard-role="filters"><div class="filter"><strong>查看范围</strong><span>全部内容品类</span><span>${escapeHtml(model.timeframe)}</span></div></section>
<div class="grid kpis"><article class="card" data-dashboard-role="kpi"><div class="kpi-label">已发布内容</div><div class="kpi-value">${formatNumber(model.kpis.published)}</div><span class="hint">按有效记录汇总</span></article><article class="card" data-dashboard-role="kpi"><div class="kpi-label">计划完成度</div><div class="kpi-value ${model.kpis.planCompletion >= 1 ? 'positive' : ''}">${formatPercent(model.kpis.planCompletion)}</div><span class="hint">已发布 / 计划数</span></article><article class="card" data-dashboard-role="kpi"><div class="kpi-label">累计浏览量</div><div class="kpi-value">${formatNumber(model.kpis.views)}</div><span class="hint">全部内容触达</span></article><article class="card" data-dashboard-role="kpi"><div class="kpi-label">转化率</div><div class="kpi-value">${formatPercent(model.kpis.conversionRate)}</div><span class="hint">转化数 / 浏览量</span></article></div>
<div class="grid two"><section data-dashboard-role="trend"><h2>浏览量趋势</h2>${trendRows}<p class="hint">柱形长度表示每日浏览量；右侧展示精确值。</p></section><section data-dashboard-role="diagnostic" class="diagnostic"><h2>经营诊断</h2><p>${escapeHtml(model.diagnostic)}</p><p class="hint">累计收入：¥${formatNumber(model.kpis.revenue)}</p></section></div>
<section data-dashboard-role="actions"><h2>建议行动</h2><div class="grid actions">${actionRows}</div></section>
<section data-dashboard-role="detail"><h2>品类表现</h2><div style="overflow:auto"><table><thead><tr><th>内容品类</th><th>发布数</th><th>浏览量</th><th>转化率</th><th>收入</th></tr></thead><tbody>${categoryRows}</tbody></table></div></section>
${trustSectionHtml({ sourceLabel: options.sourceLabel, freshness: model.freshness, semanticStatus: options.semanticStatus, evidenceCount: options.evidenceCount })}</main>${visualContractCss(visual)}</body></html>`
}
