import type { Context } from '@deepseek-ai/cordis'
import { defineTool, type JsonValue } from '@deepseek-ai/dsh-tools'
import { analyzeCsv } from './data-ingestion/csv-profile.js'
import { assessOpenMetadataEvidence, normalizeSemanticEvidenceInput } from './data-connectors/openmetadata-mcp.js'
import type { KnowledgeLibrary } from './library/knowledge-library.js'
import type { NativeWorkbenchSessions } from './native-workbench-sessions.js'

const renderJson = (_args: unknown, value: unknown) => [{ type: 'text' as const, text: JSON.stringify(value, null, 2) }]
/** The DSH ToolRuntime accepts only lossless JSON values; serialize domain records at this boundary. */
const asObject = (value: unknown): Record<string, JsonValue> => JSON.parse(JSON.stringify(value)) as Record<string, JsonValue>

export function registerWorkbenchTools(ctx: Context, library: KnowledgeLibrary, nativeSessions?: NativeWorkbenchSessions): void {
  ctx.tools.register(defineTool({
    name: 'workbench_save_generated_dashboard',
    description: 'Save a complete HTML dashboard authored directly by the Agent as a private draft for user preview. This action never publishes the dashboard or adds it to “我的看板”; the user must preview it and explicitly confirm publication in the workbench UI. The Agent independently chooses the dashboard structure and implementation from the user request and data.',
    parameters: {
      assetId: { type: 'string', required: true, description: 'Stable lowercase dashboard asset id.' },
      html: { type: 'string', required: true, description: 'Complete HTML document generated by the Agent.' },
      title: { type: 'string', description: 'Optional user-facing title.' },
      summary: { type: 'string', description: 'Optional concise delivery note.' },
      csv: { type: 'string', description: 'Optional original CSV content for the revision record.' },
      sourceLabel: { type: 'string', description: 'Optional user-facing source label.' },
    },
    output: { schema: { type: 'object', additionalProperties: true }, render: renderJson },
    execute: async (args, exec) => {
      const stored = await library.buildAgentNativeDraft({
        assetId: args.assetId,
        html: args.html,
        title: typeof args.title === 'string' ? args.title : undefined,
        summary: typeof args.summary === 'string' ? args.summary : undefined,
        csv: typeof args.csv === 'string' ? args.csv : undefined,
        sourceLabel: typeof args.sourceLabel === 'string' ? args.sourceLabel : undefined,
      })
      const sessionId = exec.agent ? String(exec.agent.session.id) : undefined
      if (sessionId && nativeSessions) await nativeSessions.recordDraft(sessionId, { assetId: stored.asset.assetId, revision: stored.revision.revision, title: stored.asset.displayName })
      return asObject({ asset: stored.asset, revision: stored.revision, manifest: stored.manifest, generationMode: 'native-dsh', workbenchUrl: sessionId ? `/?workbench=1&nativeSession=${encodeURIComponent(sessionId)}` : '/?workbench=1', nextAction: '返回工作台预览草稿；发布需要用户明确确认。' })
    },
    presentCall: () => ({ card: 'generic', title: 'Save native DSH dashboard', kind: 'execute' }),
  }))

  ctx.tools.register(defineTool({
    name: 'workbench_assess_semantic_evidence',
    description: 'Optionally normalize OpenMetadata evidence for the Agent. It is advisory context only and never blocks dashboard generation.',
    parameters: {
      evidence: { type: 'object', required: true, additionalProperties: true, description: 'Selected OpenMetadata assets with FQN, definition or glossary terms, and the exact MCP evidence tools used. Do not include access tokens, SQL, or raw connection details.' },
    },
    output: { schema: { type: 'object', additionalProperties: true }, render: renderJson },
    execute: async (args) => asObject(assessOpenMetadataEvidence(normalizeSemanticEvidenceInput(args.evidence))),
    presentCall: () => ({ card: 'generic', title: 'Assess OpenMetadata semantic evidence', kind: 'read' }),
  }))

  ctx.tools.register(defineTool({
    name: 'workbench_analyze_dataset',
    description: 'Optionally inspect a CSV schema and sample values. This is informational only; the Agent may generate a dashboard without calling it.',
    parameters: {
      csv: { type: 'string', required: true, description: 'CSV content to analyze. Never include credentials or unrelated private data.' },
    },
    output: { schema: { type: 'object', additionalProperties: true }, render: renderJson },
    execute: async (args) => asObject(analyzeCsv(args.csv)),
    presentCall: () => ({ card: 'generic', title: 'Analyze dashboard dataset', kind: 'read' }),
  }))

}
