import {serverPublishingBehavior} from './server-publishing-ui.js'
import {dashboardSharingStyles} from './dashboard-sharing-styles.js'
import {inspectorIcons} from '../live-dashboard/inspector-icons.js'
import {sharingIcons} from './sharing-icons.js'

/** Link-dependent sharing workflow; server endpoints remain the authority. */
export function dashboardSharingBehavior(): string {
 return String.raw`(()=>{
const style=document.createElement('style');style.textContent=${JSON.stringify(dashboardSharingStyles)};document.head.append(style);
const icons=${JSON.stringify({...inspectorIcons,...sharingIcons})};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>Number.isFinite(Date.parse(v))?new Date(v).toLocaleString('zh-CN',{year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'未提供';
const version=v=>/^rev-\d+$/.test(v||'')?'v'+Number(v.slice(4)):v||'版本未提供';
const icon=name=>'<span aria-hidden="true">'+(icons[name]||'')+'</span>';
const button=(attr,label,cls='')=>'<button type="button" '+attr+' class="'+cls+'">'+label+'</button>';
let modal=null,previous=null,model=null,busy=false,days=7,feedback='',openSerial=0,view='main',selectedKey='',newKey='',accessOpen=false,fsOpen=false,previewOpen=false,fsState=null,fsSelected=null,note='',fsSearchSerial=0,fsSearchTimer=0,searchText='',fsError='',linkError='',validation='',preview=null,previewSerial=0,sendAttempt=null,sent=null,confirmToken=null,oldOverflow='',oldScroll=0,expiryTimer=0,configOpen=false,creationUncertain=false;
// Raw live tokens are not persisted by the backend; retain URLs only in page memory.
const knownUrls=new Map();
const key=s=>s?String(s.delivery==='server'?'server:'+s.url:s.token):'';
const active=s=>s&&s.revision===model.revision&&(s.delivery==='server'||s.status==='active'&&Date.parse(s.expiresAt)>Date.now());
const candidates=()=>[...(model.serverPublication?[model.serverPublication]:[]),...(model.shares||[])].filter(s=>active(s)&&s.url);
const current=()=>candidates().find(s=>key(s)===selectedKey);
const api=id=>(location.pathname.startsWith('/dsh-workbench')?'/api/dsh-workbench':'/api')+'/dashboards/'+encodeURIComponent(id)+'/shares';
async function request(url,method='GET',data){let response,value;try{response=await fetch(url,{method,signal:AbortSignal.timeout(45000),headers:{'content-type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});value=await response.json()}catch{throw Object.assign(Error('请求结果未确认，请先重新核查状态'),{uncertain:true})}if(!response.ok)throw Error(String(value.error||'操作失败，请稍后重试').replace(/^PUBLISH_[A-Z_]+:/,''));return value}
const call=(method,data)=>request(api(model.id),method,data);
const fsCall=(method,data)=>request(api(model.id).replace(/shares$/,'feishu'),method,data);
function close(){if(busy)return;openSerial++;previewSerial++;fsSearchSerial++;clearTimeout(fsSearchTimer);clearInterval(expiryTimer);modal?.remove();modal=null;document.body.style.overflow=oldOverflow;window.scrollTo(0,oldScroll);previous?.focus({preventScroll:true})}
function absorb(data){const id=model.id;Object.assign(model,data);model.shares=(data.shares||[]).map(s=>({...s,url:s.url||knownUrls.get(id+':'+s.token)||''}));const list=candidates();if(!selectedKey&&list.length===1)selectedKey=key(list[0]);if(selectedKey&&!current()){linkError='当前链接已失效或不再匹配此版本，请选择其他链接或重新生成。';validation='';preview=null}}
function select(s){selectedKey=key(s);newKey='';validation='';linkError='';preview=null;previewSerial++;sendAttempt=null;sent=null;render();if(previewOpen)void validate(true)}
function permission(s){return s?.access==='jupyter'||!s&&model.live&&model.serverDeployUrl?'仅限具备 Jupyter 登录权限并连接公司网络的用户访问。':model.lan?'持链接且可连接本机的公司内网用户可查看；请保持本机在线。':'持链接者可查看；转发链接也会传递访问权。'}
function linkPayload(s){return {token:s.token,url:s.url,delivery:s.delivery}}
async function load(){const serial=openSerial;model.loading=true;model.failed=false;feedback='';render();try{const data=await call('GET');if(serial!==openSerial)return;absorb(data);try{const state=await fsCall('GET');if(serial!==openSerial)return;fsState=state}catch{fsState={unavailable:true}}}catch(e){if(serial===openSerial){model.failed=true;feedback=e.message}}finally{if(serial===openSerial){model.loading=false;render()}}}
async function validate(showPreview=false){const s=current();if(!s||busy)return false;const serial=++previewSerial,opened=openSerial,context=selectedKey;validation='正在校验…';linkError='';render();try{const data=await call('GET');if(serial!==previewSerial||opened!==openSerial||context!==selectedKey)return false;absorb(data);if(!current())throw Error('当前链接已失效或不再匹配此版本');const result=await fsCall('POST',{action:'preview',...linkPayload(current()),note});if(serial!==previewSerial||opened!==openSerial||context!==selectedKey)return false;validation='当前版本与链接已通过服务端预检（不代表接收人已获权限）';if(showPreview)preview=result.card;render();return true}catch(e){if(serial===previewSerial&&opened===openSerial&&context===selectedKey){validation='校验未通过';linkError=e.message;preview=null;render()}return false}}
async function generate(){if(busy||model.failed||model.loading||creationUncertain)return;busy=true;feedback='';linkError='';render();try{const result=await call('POST',{days});knownUrls.set(model.id+':'+result.token,result.url);model.shares=[result,...model.shares.filter(s=>s.token!==result.token)];selectedKey=key(result);newKey=result.reused?'':selectedKey;validation='';preview=null;previewSerial++;sendAttempt=null;sent=null}catch(e){feedback=e.message;creationUncertain=Boolean(e.uncertain);try{absorb(await call('GET'));if(current())creationUncertain=false}catch{feedback+='；暂时无法核查链接，请重新加载后再试';model.failed=true}}finally{busy=false;render()}}
${serverPublishingBehavior()}
async function deploy(){if(busy||model.isDraft)return;const popup=window.open('about:blank','dsh-server-publish','width=860,height=650');busy=true;feedback='请在服务器窗口完成登录和版本校验。';render();try{model.serverPublication=await window.dshDeployReleased({assetId:model.id,publishUrl:model.serverDeployUrl,popup});selectedKey=key(model.serverPublication);newKey=selectedKey;feedback='';linkError='';validation='';preview=null;sendAttempt=null;sent=null}catch(e){feedback=e.message}finally{busy=false;render()}}
async function revoke(){if(busy)return;busy=true;render();try{await call('DELETE',{token:confirmToken});model.shares=model.shares.map(s=>s.token===confirmToken?{...s,status:'revoked'}:s);knownUrls.delete(model.id+':'+confirmToken);if(selectedKey===confirmToken){linkError='链接已撤销，请选择其他链接或重新生成。';preview=null;validation='';previewSerial++}confirmToken=null}catch(e){feedback=e.message}finally{busy=false;render()}}
async function copy(s,element){try{await navigator.clipboard.writeText(s.url);element.innerHTML=icon('copy')+'已复制';setTimeout(()=>{if(element.isConnected)element.innerHTML=icon('copy')+'复制'},1800)}catch{feedback='复制失败，请选中完整链接后按 Ctrl+C 复制';render();const input=modal.querySelector('[data-url]');input?.focus();input?.select()}}
function cardHtml(card){if(!card)return '';return '<div class="bs-card"><div class="bs-card-header">'+esc(card.header?.title?.content)+'<small class="bs-field">'+esc(card.header?.subtitle?.content)+'</small></div><div class="bs-card-body">'+(card.body?.elements||[]).map(e=>e.tag==='div'?'<p>'+esc(e.text?.content)+'</p>':e.tag==='button'?'<span class="bs-card-action">'+esc(e.text?.content)+'</span>':'').join('')+'</div></div><p>内容来自实际消息卡片；最终排版以飞书客户端为准。</p>'}
function feishu(s){
 if(!s)return '<section class="bs-divider"><h3>飞书发送（可选）</h3><div class="bs-locked">'+icon('lock')+'请先生成分享链接</div></section>';
 let html='<section class="bs-divider">'+button('data-fs-toggle aria-expanded="'+fsOpen+'" aria-controls="bs-feishu"','<span class="bs-chevron">'+icon('chevron')+'</span>发送到飞书（可选）','bs-text');if(!fsOpen)return html+'</section>';
 html+='<div id="bs-feishu"><p>将发送上方分享链接。</p>';
 if(sent)return html+'<div class="bs-status" role="status">已发送到飞书</div><p>接收人：'+esc(sent.name)+'</p><div class="bs-footer">'+button('data-continue','继续分享','bs-text')+button('data-close','完成','bs-primary')+'</div></div></section>';
 if(fsState?.unavailable)return html+'<p class="bs-error">暂时无法读取应用连接状态</p>'+button('data-fs-retry','重试','bs-text')+'</div></section>';
 if(!fsState?.configured||configOpen)return html+'<p>接收人搜索需要本机飞书 CLI 通讯录授权。配置仅影响发送身份，不授予看板访问权限。</p><form data-config><label>App ID<input class="bs-field" name="appId" required autocomplete="off"></label><label>App Secret<input class="bs-field" name="appSecret" type="password" required autocomplete="new-password"></label><p>凭据仅存储在本机服务端。</p><button type="submit" class="bs-primary">保存并验证</button>'+button('data-config-back','返回发送','bs-text')+'</form></div></section>';
 html+='<form data-send><label for="bs-person">接收人</label><div class="bs-recipient">'+(fsSelected?'<span class="bs-chip"><span title="'+esc(fsSelected.name)+'">'+esc(fsSelected.name)+'</span>'+button('data-remove-person aria-label="移除接收人"',icon('close'))+'</span>':'<input id="bs-person" type="search" name="recipient" aria-label="搜索姓名或工号" placeholder="搜索姓名或工号" maxlength="50" autocomplete="off" value="'+esc(searchText)+'">')+'</div><div data-results role="region" aria-label="同事搜索结果"></div><p>'+esc(fsSelected?.department||fsSelected?.email||'请输入关键词，并从结果中选择一位同事。')+'</p><label for="bs-note">附言（选填）</label><textarea id="bs-note" name="note" maxlength="500" placeholder="给对方留句话…">'+esc(note)+'</textarea><p>最多 500 字</p>'+button('data-preview aria-expanded="'+previewOpen+'" aria-controls="bs-preview"','<span class="bs-chevron">'+icon('chevron')+'</span>消息预览','bs-text')+(previewOpen?'<div id="bs-preview">'+(preview?cardHtml(preview):'<p>'+esc(validation||'尚未预检')+'</p>')+'</div>':'')+'<div class="bs-feedback bs-error" role="status">'+esc(fsError)+'</div>'+(!fsSelected?'<p>请选择接收人后发送。</p>':'')+(sendAttempt?'<p>本次发送内容已锁定，核查重试会沿用原编号，避免重复发送。</p>':'')+'<div class="bs-footer"><p>通过应用机器人发送</p><button class="bs-primary" type="submit" '+(busy||!fsSelected||linkError?'disabled':'')+'>'+(busy?'发送中…':sendAttempt?'核查并重试发送':'发送到飞书')+'</button></div></form></div></section>';return html;
}
function render(){
 if(!modal)return;const focused=document.activeElement,focusKey=focused?.id;const focusAttr=focused?.getAttributeNames?.().find(n=>n.startsWith('data-'));const scroll=modal.querySelector('.board-share-dialog')?.scrollTop||0;const s=current(),records=model.shares||[],list=candidates();
 let html='<section class="board-share-dialog" role="dialog" aria-modal="true" aria-labelledby="bs-title" tabindex="-1"><div class="bs-head"><h2 id="bs-title">分享看板</h2>'+button('data-close aria-label="关闭" data-tooltip="关闭"',icon('close'),'bs-icon')+'</div><div class="bs-board"><div class="bs-board-name" title="'+esc(model.title)+'">'+esc(model.title)+'</div><p>'+esc(version(s?.revision||model.revision))+' · '+(model.live===undefined?'查询模式待确认':model.live?'实时查询':'只读快照')+(model.isDraft?' · 草稿':'')+'</p></div>';
 if(view==='manage'){html+=button('data-back',icon('chevron')+'返回分享','bs-text')+'<h3>管理已有链接</h3>'+(!records.length?'<p>暂无可管理的链接。服务器入口请通过原部署管理维护。</p>':records.map(r=>'<div class="bs-record">'+esc(version(r.revision))+'<p>'+(r.status==='revoked'?'已撤销':Date.parse(r.expiresAt)<=Date.now()?'已过期':'有效期至 '+date(r.expiresAt))+'</p>'+(!r.url?'<p>服务端仅保存令牌摘要，无法恢复完整链接；仍可撤销。</p>':'')+'<div class="bs-record-actions">'+(active(r)&&r.url?button('data-select="'+esc(key(r))+'"','使用此链接')+button('data-copy-record="'+esc(key(r))+'"','复制'):'')+(r.status==='active'&&Date.parse(r.expiresAt)>Date.now()?button('data-revoke="'+esc(r.token)+'"','撤销链接','bs-danger'):'')+'</div>'+(confirmToken===r.token?'<div class="bs-confirm">撤销后已发出的链接将无法访问。'+button('data-cancel-revoke','取消')+button('data-confirm-revoke','确认撤销','bs-danger')+'</div>':'')+'</div>').join(''));
 }else if(model.loading)html+='<p role="status">正在读取分享状态…</p>';else if(model.failed)html+='<p class="bs-error" role="alert">暂时无法获取分享链接</p>'+button('data-retry','重试','bs-text');else{
 html+='<div class="bs-between"><h3>分享链接</h3>'+(s?'<span class="bs-status">'+(linkError?icon('info'):icon('check'))+(linkError?'待校验':newKey===selectedKey?'已生成':'可用')+'</span>':'')+'</div>';
 if(list.length>1)html+='<label for="bs-links">选择适用链接</label><select id="bs-links" class="bs-field"><option value="">请选择链接</option>'+list.map((l,i)=>'<option value="'+esc(key(l))+'" '+(key(l)===selectedKey?'selected':'')+'>'+esc(l.delivery==='server'?'服务器版本':version(l.revision)+' · '+date(l.expiresAt)+' 到期 · 链接 '+(i+1))+'</option>').join('')+'</select>';
 html+=s?'<div class="bs-link"><input data-url aria-label="分享链接" readonly title="'+esc(s.url)+'" value="'+esc(s.url)+'">'+button('data-copy aria-label="复制链接"',icon('copy')+'复制')+'</div>':'<p>生成后可复制链接，或通过飞书发送。</p>';
 html+='<p class="bs-permission">'+icon('lock')+esc(permission(s))+'</p>';
 if(s)html+='<p>'+(s.delivery==='server'?'此服务器入口未设置分享有效期。':'有效期至 '+date(s.expiresAt))+'</p>';else if(model.live&&model.serverDeployUrl)html+=button('data-deploy '+(model.isDraft?'disabled':''),model.isDraft?'请先发布看板':busy?'生成中…':'生成分享链接','bs-primary')+'<p>将当前发布版本部署到服务器，并完成原有登录及校验流程。</p>';else html+='<div class="bs-settings"><label for="bs-days">有效期</label><select id="bs-days">'+[1,7,30].map(n=>'<option '+(n===days?'selected':'')+' value="'+n+'">'+n+' 天</option>').join('')+'</select></div>'+button('data-generate',busy?'生成中…':'生成分享链接','bs-primary');
 if(!s&&records.some(r=>active(r)&&!r.url))html+='<p>已有链接记录无法恢复完整 URL。可管理原链接，或显式生成新链接。</p>';
 if(creationUncertain&&!s)html+='<p class="bs-error">上次生成结果未确认。请先在管理链接中核查，避免重复创建。</p>'+button('data-confirm-new','已核查，仍需生成新链接','bs-text');
 html+='<div class="bs-feedback bs-error" role="alert">'+esc(linkError)+'</div><div class="bs-meta">'+button('data-access aria-expanded="'+accessOpen+'" aria-controls="bs-access"','访问与版本信息 '+icon('chevron'),'bs-text')+button('data-manage','管理'+(s?'':'已有')+'链接 '+icon('chevron'),'bs-text')+'</div>';
 if(accessOpen)html+='<div class="bs-access" id="bs-access"><dl><dt>内部版本</dt><dd>'+esc(s?.revision||model.revision)+'</dd><dt>访问要求</dt><dd>'+esc(permission(s))+'</dd><dt>服务器校验</dt><dd>'+esc(validation||'尚未进行本次预检')+'</dd></dl>'+(s?button('data-validate','重新校验','bs-text'):'')+(s?.verifiedAt?'<p>发布登记时间：'+date(s.verifiedAt)+'（不是实时连通性结论）</p>':'')+'</div>';
 if(accessOpen&&s&&fsState?.configured&&fsState.mode!=='cli')html+=button('data-config-open','应用配置','bs-text');
 if(accessOpen&&s&&model.live&&model.serverDeployUrl)html+=button('data-deploy','重新核验服务器版本','bs-text');
 if(linkError&&s)html+=button('data-validate','重新校验','bs-text');html+=feishu(s);
 }
 html+='<div class="bs-feedback bs-error" role="status">'+esc(feedback)+'</div></section>';modal.innerHTML=html;
 const on=(q,fn)=>modal.querySelectorAll(q).forEach(el=>el.addEventListener('click',fn));
 on('[data-config-back]',()=>{configOpen=false;render()});on('[data-config-open]',()=>{configOpen=true;fsOpen=true;render()});on('[data-confirm-new]',()=>{creationUncertain=false;feedback='';render()});on('[data-close]',close);on('[data-retry]',load);on('[data-generate]',generate);on('[data-deploy]',deploy);on('[data-copy]',e=>copy(s,e.currentTarget));on('[data-manage]',()=>{view='manage';render();modal.querySelector('[data-back]')?.focus()});on('[data-back]',()=>{view='main';render()});on('[data-access]',()=>{accessOpen=!accessOpen;render()});on('[data-validate]',()=>validate(previewOpen));on('[data-fs-toggle]',()=>{fsOpen=!fsOpen;render()});on('[data-preview]',()=>{previewOpen=!previewOpen;render();if(previewOpen)void validate(true)});
 on('[data-select]',e=>{view='main';select(list.find(l=>key(l)===e.currentTarget.dataset.select))});on('[data-copy-record]',e=>copy(records.find(r=>key(r)===e.currentTarget.dataset.copyRecord),e.currentTarget));on('[data-revoke]',e=>{confirmToken=e.currentTarget.dataset.revoke;render()});on('[data-cancel-revoke]',()=>{confirmToken=null;render()});on('[data-confirm-revoke]',revoke);
 on('[data-remove-person]',()=>{fsSelected=null;searchText='';fsError='';render();modal.querySelector('#bs-person')?.focus()});on('[data-continue]',()=>{sent=null;sendAttempt=null;fsSelected=null;note='';searchText='';preview=null;previewOpen=false;fsError='';render()});on('[data-fs-retry]',load);
 modal.querySelector('#bs-links')?.addEventListener('change',e=>select(list.find(l=>key(l)===e.target.value)));modal.querySelector('#bs-days')?.addEventListener('change',e=>days=Number(e.target.value));
 modal.querySelector('#bs-note')?.addEventListener('input',e=>{note=e.target.value;preview=null;previewSerial++;const p=modal.querySelector('#bs-preview');if(p)p.innerHTML='<p>附言已更新，请重新展开预览。</p>'});
 modal.querySelector('#bs-person')?.addEventListener('input',search);modal.querySelector('[data-send]')?.addEventListener('submit',send);modal.querySelector('[data-config]')?.addEventListener('submit',configure);
 if(creationUncertain)modal.querySelector('[data-generate]')?.setAttribute('disabled','');
 if(busy)modal.querySelectorAll('button,input,select,textarea').forEach(el=>el.disabled=true);
 if(sendAttempt)modal.querySelectorAll('#bs-person,#bs-note,[data-remove-person],#bs-links,[data-select],[data-generate],[data-deploy]').forEach(el=>el.disabled=true);
 const dialog=modal.querySelector('.board-share-dialog');dialog.scrollTop=scroll;if(focusKey)modal.querySelector('#'+CSS.escape(focusKey))?.focus({preventScroll:true});else if(focusAttr)modal.querySelector('['+focusAttr+']')?.focus({preventScroll:true});if(!modal.contains(document.activeElement))dialog.focus({preventScroll:true});
}
function search(e){searchText=e.target.value;const query=searchText.trim(),serial=++fsSearchSerial,opened=openSerial,results=modal.querySelector('[data-results]');clearTimeout(fsSearchTimer);results.textContent=query?'正在搜索…':'';if(!query)return;fsSearchTimer=setTimeout(async()=>{try{const found=await fsCall('POST',{action:'search',query});if(serial!==fsSearchSerial||opened!==openSerial||!results.isConnected)return;results.innerHTML=found.users.length?found.users.map((u,i)=>button('data-person="'+i+'"',esc(u.name)+'<small>'+esc(u.department||'部门未提供')+' · '+esc(u.email)+'</small>','bs-person')).join('')+(found.hasMore?'<p>还有更多同事，请输入更完整关键词。</p>':''):'<p>没有找到同事，请尝试完整姓名或工号。</p>';results.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{fsSelected=found.users[Number(b.dataset.person)];fsSearchSerial++;searchText='';render()})}catch(e){if(serial===fsSearchSerial&&results.isConnected)results.textContent=e.message}},400)}
async function configure(e){e.preventDefault();if(busy)return;const data=new FormData(e.target);busy=true;feedback='';render();try{fsState=await fsCall('POST',{action:'configure',appId:String(data.get('appId')).trim(),appSecret:String(data.get('appSecret')).trim()});configOpen=false}catch(e){feedback=e.message}finally{busy=false;render()}}
async function send(e){e.preventDefault();if(busy||sent||!fsSelected||!current()||linkError)return;const snapshot=sendAttempt||{...linkPayload(current()),key:selectedKey,userId:fsSelected.id,name:fsSelected.name,note,requestId:crypto.randomUUID()};busy=true;fsError='';previewSerial++;render();let submitted=false;try{absorb(await call('GET'));if(!current()||selectedKey!==snapshot.key)throw Error('链接已失效或版本已变化，请重新选择');await fsCall('POST',{action:'preview',...snapshot});sendAttempt=snapshot;submitted=true;const result=await fsCall('POST',{action:'send',...snapshot});if(!result.messageId)throw Error('发送结果未确认，请核查飞书收件情况');sent={name:snapshot.name};validation='发送前已通过服务端预检'}catch(e){fsError=e.message;if(submitted)fsError+='；如结果未确认，请先核查飞书。重试沿用原请求编号，不会重新生成链接。';else{linkError=e.message}}finally{busy=false;render()}}
document.addEventListener('dsh:share-dashboard',event=>{if(modal)return;previous=document.activeElement;model={id:event.detail.id,title:event.detail.title,shares:[],lan:true};days=7;feedback='';view='main';selectedKey='';newKey='';accessOpen=false;fsOpen=false;previewOpen=false;fsState=null;fsSelected=null;note='';searchText='';fsError='';linkError='';validation='';preview=null;sendAttempt=null;sent=null;confirmToken=null;configOpen=false;creationUncertain=false;openSerial++;oldOverflow=document.body.style.overflow;oldScroll=window.scrollY;document.body.style.overflow='hidden';modal=document.createElement('div');modal.className='board-share-backdrop';document.body.append(modal);modal.addEventListener('click',e=>{if(e.target===modal)close()});modal.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const nodes=[...modal.querySelectorAll('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),select:not(:disabled)')].filter(n=>n.getClientRects().length);const first=nodes[0],last=nodes[nodes.length-1];if(!nodes.length){e.preventDefault();return}if(e.shiftKey&&(document.activeElement===first||document.activeElement===modal.querySelector('[role=dialog]'))){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});void load();modal.querySelector('[data-close]')?.focus();expiryTimer=setInterval(()=>{if(!busy&&selectedKey&&!current()&&!linkError){linkError='链接已过期，请选择其他链接或重新生成。';preview=null;previewSerial++;render()}},1000)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal){e.preventDefault();e.stopImmediatePropagation();close()}},true);
})();`
}
