export function dashboardSharingBehavior(): string {
  return String.raw`(()=>{
const style=document.createElement('style');style.textContent='.board-share-backdrop{position:fixed;inset:0;z-index:10000;background:#0005;display:grid;place-items:center;padding:20px}.board-share-dialog{width:min(460px,100%);max-height:85vh;overflow:auto;background:white;border:1px solid #e8e8e8;border-radius:14px;padding:24px;box-sizing:border-box;box-shadow:0 16px 60px #0002;color:#292929;font:13px/1.6 system-ui}.board-share-dialog h2{font-size:18px;margin:0 0 20px}.board-share-dialog h3{font-size:14px;font-weight:500;margin:0 0 5px;overflow-wrap:anywhere}.board-share-dialog p{margin:8px 0;color:#858585;font-size:12px}.board-share-dialog button,.board-share-dialog select{font:inherit;border:1px solid #dedede;border-radius:7px;background:white;padding:7px 12px;cursor:pointer;color:inherit}.board-share-dialog button:disabled{opacity:.5;cursor:wait}.board-share-dialog .bs-close{float:right;border:0;padding:0 6px;font-size:22px;color:#888}.board-share-dialog .bs-row{display:flex;justify-content:space-between;align-items:center;gap:12px;margin:20px 0}.board-share-dialog .bs-primary{background:#222;color:white;border-color:#222;width:100%;padding:10px}.board-share-dialog .bs-link{display:flex;gap:8px;margin-top:16px}.board-share-dialog input{min-width:0;flex:1;border:1px solid #dedede;border-radius:7px;padding:9px;font:12px system-ui;color:#555;background:#fafafa}.board-share-dialog details{border-top:1px solid #eee;margin-top:20px;padding-top:14px}.board-share-dialog summary{cursor:pointer;color:#777}.board-share-dialog .bs-record{margin-top:14px;padding-top:10px;border-top:1px solid #f2f2f2;display:flex;justify-content:space-between;align-items:center;gap:10px}.board-share-dialog .bs-danger{color:#b83a34;font-size:12px}.board-share-dialog .bs-feedback{min-height:20px;color:#a34235}.board-share-dialog .bs-confirm{background:#faf5f4;padding:12px;border-radius:8px;margin-top:10px}.board-share-dialog :focus-visible{outline:2px solid #777;outline-offset:2px}';document.head.append(style);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>new Date(v).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
let modal=null,previous=null,model=null,busy=false,days=7,confirmToken=null,feedback='',openSerial=0;
const api=id=>(location.pathname.startsWith('/dsh-workbench')?'/api/dsh-workbench':'/api')+'/dashboards/'+encodeURIComponent(id)+'/shares';
const close=()=>{if(busy)return;openSerial++;modal?.remove();modal=null;previous?.focus()};
async function call(method,data){const response=await fetch(api(model.id),{method,headers:{'content-type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});const value=await response.json();if(!response.ok)throw new Error(String(value.error||'操作失败，请重试').replace(/^PUBLISH_[A-Z_]+:/,''));return value}
const active=s=>s.status==='active'&&Date.parse(s.expiresAt)>Date.now();
function render(){if(!modal)return;const current=model.shares?.find(s=>s.revision===model.revision&&active(s));const records=model.shares||[];
modal.innerHTML='<section class="board-share-dialog" role="dialog" aria-modal="true" aria-labelledby="bs-title"><button class="bs-close" aria-label="关闭分享" '+(busy?'disabled':'')+'>×</button><h2 id="bs-title">分享看板</h2><h3>'+esc(model.title)+'</h3><p>'+esc(model.revision||'')+' · 只读快照'+(model.isDraft?' · 当前草稿快照':'')+'</p>'+(model.loading?'<p>正在读取分享状态…</p>':model.failed?'<button data-retry>重新加载</button>':current?'<div class="bs-link"><input aria-label="分享链接" readonly value="'+esc(current.url)+'"><button data-copy>复制链接</button></div><p>有效期至 '+date(current.expiresAt)+' · 可复制后粘贴到飞书</p>':'<div class="bs-row"><label for="bs-days">链接有效期</label><select id="bs-days" '+(busy?'disabled':'')+'>'+[1,7,30].map(n=>'<option value="'+n+'" '+(days===n?'selected':'')+'>'+n+' 天</option>').join('')+'</select></div><button class="bs-primary" data-generate '+(busy?'disabled':'')+'>'+(busy?'正在生成…':records.some(active)?'为当前版本生成链接':'生成分享链接')+'</button>')+'<p>'+(model.lan?'持链接且可连接本机的公司内网用户可查看。请保持本机联网、运行且不休眠。':'持链接者可查看；转发链接也会传递访问权。')+'</p><div class="bs-feedback" role="status">'+esc(feedback)+'</div>'+(records.length?'<details '+(confirmToken?'open':'')+'><summary>管理分享链接 · '+records.length+'</summary>'+records.map(s=>'<div class="bs-record"><span>'+esc(s.revision)+'<br><small>'+(!active(s)?s.status==='revoked'?'已撤销':'已过期':'有效至 '+date(s.expiresAt))+'</small></span>'+(active(s)?'<button class="bs-danger" data-revoke="'+esc(s.token)+'" '+(busy?'disabled':'')+'>撤销链接</button>':'')+'</div>'+(confirmToken===s.token?'<div class="bs-confirm">撤销后，已发出的链接将无法继续访问。<div class="bs-row"><button data-cancel-revoke '+(busy?'disabled':'')+'>取消</button><button class="bs-danger" data-confirm-revoke '+(busy?'disabled':'')+'>'+(busy?'正在撤销…':'确认撤销')+'</button></div></div>':'')).join('')+'</details>':'')+'</section>';
renderFeishu(current);
modal.querySelector('.bs-close').onclick=close;modal.querySelector('[data-retry]')?.addEventListener('click',()=>load());modal.querySelector('#bs-days')?.addEventListener('change',e=>days=Number(e.target.value));
modal.querySelector('[data-generate]')?.addEventListener('click',()=>mutate('POST',{days}));
modal.querySelector('[data-copy]')?.addEventListener('click',async e=>{const input=modal.querySelector('input');try{await navigator.clipboard.writeText(current.url);e.target.textContent='已复制'}catch{input.focus();input.select();if(document.execCommand('copy'))e.target.textContent='已复制';else modal.querySelector('.bs-feedback').textContent='链接已选中，请按 Ctrl+C 复制'} });
modal.querySelectorAll('[data-revoke]').forEach(b=>b.onclick=()=>{confirmToken=b.dataset.revoke;render();modal.querySelector('[data-cancel-revoke]')?.focus()});modal.querySelector('[data-cancel-revoke]')?.addEventListener('click',()=>{confirmToken=null;render()});modal.querySelector('[data-confirm-revoke]')?.addEventListener('click',()=>mutate('DELETE',{token:confirmToken}));}
let fsSelected=null,fsSearchSerial=0,fsSearchTimer=null;
let fsState=null,fsMode='',fsDraft={email:'',note:''},fsRequest='',fsSent=false;
async function fsCall(method,data){const r=await fetch(api(model.id).replace(/shares$/,'feishu'),{method,headers:{'content-type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});const v=await r.json();if(!r.ok)throw new Error(String(v.error||'操作失败').replace(/^PUBLISH_[A-Z_]+:/,''));return v}
function renderFeishu(current){
 if(model.loading||model.failed)return;
 const panel=document.createElement('div');panel.style.cssText='border-top:1px solid #eee;padding-top:14px;margin-top:14px';
 const disabled=busy?'disabled':'';
 if(fsState?.configured&&fsState.mode==='cli'&&fsMode==='config')fsMode='';
 panel.innerHTML='<h3>飞书分享</h3>'+(fsMode==='config'?'<p>在飞书开放平台启用应用机器人，申请 im:message:send_as_bot 权限，发布应用并将试用同事加入可见范围。</p><form data-fs-config><label>App ID<input name="appId" aria-label="App ID" required value="'+esc(fsState?.appId||'')+'" style="display:block;width:100%;box-sizing:border-box"></label><label>App Secret<input name="appSecret" aria-label="App Secret" type="password" autocomplete="new-password" required style="display:block;width:100%;box-sizing:border-box"></label><p>凭据仅存储在本机服务端，不会出现在分享链接中。</p><button '+disabled+' type="submit">'+(busy?'正在验证…':'保存并验证')+'</button> <button type="button" data-fs-back '+disabled+'>返回</button></form>':fsMode==='send'&&current?'<form data-fs-send><label>接收人<input type="search" name="recipient" aria-label="搜索姓名或工号" placeholder="搜索姓名或工号" autocomplete="off" maxlength="50" value="'+esc(fsSelected?.name||'')+'" style="display:block;width:100%;box-sizing:border-box" '+(fsRequest?'readonly':'')+'></label><div data-fs-results role="region" aria-label="同事搜索结果" style="max-height:200px;overflow:auto"></div><div data-fs-selected>'+ (fsSelected?'<p>已选择：'+esc(fsSelected.name)+' · '+esc(fsSelected.department||fsSelected.email)+'</p>':'<p>输入关键词后，从搜索结果中选择同事。</p>')+'</div><label>附言（选填）<input name="note" aria-label="附言" maxlength="500" value="'+esc(fsDraft.note)+'" style="display:block;width:100%;box-sizing:border-box" '+(fsRequest?'readonly':'')+'></label><div style="border:1px solid #dbe4f5;border-radius:8px;overflow:hidden;margin:14px 0"><div style="background:#eaf1ff;padding:12px;color:#2358aa">'+esc(model.title)+'</div><div style="padding:12px"><span>'+esc(current.revision)+' · 只读快照</span><p>有效期至 '+date(current.expiresAt)+'</p><p data-fs-note style="white-space:pre-wrap;overflow-wrap:anywhere">'+esc(fsDraft.note)+'</p><p>持链接者可查看，请连接公司网络。</p><span style="display:block;background:#3370ff;color:white;text-align:center;border-radius:6px;padding:7px">查看看板</span></div></div><p>将以应用机器人身份发送给上方接收人。预览仅示意，实际样式以飞书为准。</p><button class="bs-primary" type="submit" '+(busy||fsSent||!fsSelected?'disabled':'')+'>'+(busy?'正在发送…':fsSent?'已发送':fsRequest?'重试发送':'发送卡片')+'</button><button type="button" data-fs-back '+disabled+' style="margin-top:10px">返回</button></form>':fsState?.configured?'<p>应用已连接 · '+esc(fsState.appId)+'</p><button data-fs-open '+(!current||busy?'disabled':'')+'>发送到飞书</button>'+ (fsState.mode==='cli'?'<p>已复用本机飞书应用，无需填写密码或 App Secret。</p>':' <button data-fs-setup '+disabled+'>应用配置</button>')+(!current?'<p>请先生成分享链接。</p>':''):fsState?.unavailable?'<p>暂时无法读取应用连接状态，请重新加载分享窗口。</p>':'<p>配置飞书应用后，可直接发送看板卡片。</p><button data-fs-setup '+disabled+'>配置飞书应用</button>');
 modal.querySelector('.board-share-dialog').append(panel);
 panel.querySelector('[data-fs-setup]')?.addEventListener('click',()=>{fsMode='config';feedback='';render()});
 panel.querySelector('[data-fs-open]')?.addEventListener('click',()=>{fsMode='send';fsRequest='';fsSent=false;fsSelected=null;feedback='';render()});
 panel.querySelector('[data-fs-back]')?.addEventListener('click',()=>{fsMode='';feedback='';render()});
 panel.querySelector('[data-fs-config]')?.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const data=new FormData(e.target);busy=true;panel.querySelectorAll('button').forEach(b=>b.disabled=true);try{fsState=await fsCall('POST',{action:'configure',appId:String(data.get('appId')).trim(),appSecret:String(data.get('appSecret')).trim()});fsMode='';feedback='配置已验证，可以发送卡片；接收范围及消息权限会在发送时校验'}catch(e){feedback=e.message}finally{busy=false;render()}});
 const form=panel.querySelector('[data-fs-send]');
 form?.elements.recipient.addEventListener('input',()=>{
   fsSelected=null;form.querySelector('button[type="submit"]').disabled=true;panel.querySelector('[data-fs-selected]').textContent='';
   const query=form.elements.recipient.value.trim(),serial=++fsSearchSerial;clearTimeout(fsSearchTimer);
   const results=panel.querySelector('[data-fs-results]');results.textContent=query?'正在搜索…':'';
   if(!query)return;
   fsSearchTimer=setTimeout(async()=>{try{
     const found=await fsCall('POST',{action:'search',query});if(serial!==fsSearchSerial||!panel.isConnected)return;
     results.innerHTML=found.users.length?found.users.map((u,i)=>'<button type="button" data-person="'+i+'" style="display:block;text-align:left;width:100%;border:0;border-radius:6px;margin:4px 0;padding:10px;background:#f7f8fa"><strong style="font-weight:500">'+esc(u.name)+'</strong><small style="display:block;color:#888;overflow-wrap:anywhere">'+esc(u.department||'部门未提供')+' · '+esc(u.email)+'</small></button>').join('')+(found.hasMore?'<p>还有更多同事，请输入更完整的关键词。</p>':''):'<p>没有找到同事，请尝试完整姓名或工号。</p>';
     results.querySelectorAll('[data-person]').forEach(button=>button.onclick=()=>{fsSelected=found.users[Number(button.dataset.person)];fsSearchSerial++;form.elements.recipient.value=fsSelected.name;results.innerHTML='';panel.querySelector('[data-fs-selected]').textContent='已选择：'+fsSelected.name+' · '+(fsSelected.department||fsSelected.email);form.querySelector('button[type="submit"]').disabled=false;});
   }catch(e){if(serial===fsSearchSerial&&panel.isConnected)results.textContent=e.message}},400);
 });
 form?.elements.note.addEventListener('input',()=>{fsDraft.note=form.elements.note.value;panel.querySelector('[data-fs-note]').textContent=fsDraft.note});
 form?.addEventListener('submit',async e=>{e.preventDefault();if(busy||fsSent||!fsSelected)return;fsDraft.note=form.elements.note.value;fsRequest=fsRequest||crypto.randomUUID();busy=true;feedback='';render();try{await fsCall('POST',{action:'send',token:current.token,userId:fsSelected.id,note:fsDraft.note,requestId:fsRequest});fsSent=true;feedback='卡片已发送给 '+fsSelected.name+'，请在飞书中查看'}catch(e){feedback=e.message}finally{busy=false;render()}});
}
async function load(){const serial=openSerial;model.loading=true;model.failed=false;feedback='';render();try{const data=await call('GET');if(serial!==openSerial)return;Object.assign(model,data);try{const state=await fsCall('GET');if(serial!==openSerial)return;fsState=state}catch{fsState={unavailable:true}}}catch(e){if(serial!==openSerial)return;model.failed=true;feedback=e.message}finally{if(serial===openSerial){model.loading=false;render()}}}
async function mutate(method,data){if(busy)return;busy=true;feedback='';render();try{const result=await call(method,data);if(method==='POST'){model.shares=[result,...(model.shares||[]).filter(s=>s.token!==result.token)];feedback=result.reused?'已复用当前版本的有效链接':'链接已生成，可复制到飞书'}else{model.shares=model.shares.map(s=>s.token===data.token?{...s,status:'revoked'}:s);confirmToken=null;feedback='链接已撤销'}}catch(e){feedback=e.message}finally{busy=false;render()}}
document.addEventListener('dsh:share-dashboard',event=>{if(modal)return;previous=document.activeElement;model={id:event.detail.id,title:event.detail.title,shares:[],lan:true};days=7;confirmToken=null;feedback='';fsState=null;fsMode='';fsDraft={email:'',note:''};fsRequest='';fsSent=false;openSerial++;modal=document.createElement('div');modal.className='board-share-backdrop';document.body.append(modal);modal.addEventListener('click',e=>{if(e.target===modal)close()});modal.addEventListener('keydown',e=>{if(e.key==='Tab'){const nodes=[...modal.querySelectorAll('button:not(:disabled),input,select,summary')];const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});void load();modal.querySelector('.bs-close')?.focus()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal){e.preventDefault();e.stopImmediatePropagation();close()}},true);
})();`
}
